title: Vikram Ghadge
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Experienced Developer | Resume & Portfolio
baseurl: "/MyVC" # the subpath of your site, e.g. /blog
url: "https://vikramghadge.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
